### ISSUE TITLE
[Fix] 여행 규칙 코멘트

### ISSUE THREAD

**Issue by yewonahn** [Here-You/here-you-backend#108]
## 이슈 번호 
108

## To-do
- [ ] 댓글 수정 기능
- [ ] 댓글 삭제 기능
- [ ] (예외 상황 고려)
