### ISSUE TITLE
[Fix] 메이트 탐색 데이터 누락 및 오류 수정 

### ISSUE THREAD

**Issue by JangYouJung** [Here-You/here-you-backend#115]
## Description
설명을 작성해주세요.

## To-do
- [x] 팔로우 여부 반영 안되는 오류 수정
- [x] 시그니처 상세보기: author 정보 누락
- [x] 장소 기준 탐색: 가장 최신 시그니처 두 개가 아닌 관련 시그니처를 가져오도록 구현
- [x] 랜덤 탐색에서 본인은 제외

## ETC
기타 참고사항을 적어주세요.
