### ISSUE TITLE
[STYLE ] 홈 : 코드 정리 

### ISSUE THREAD

**Issue by moonyaeyoon** [Here-You/here-you-backend#121]
## Description
API 마무리 -> 함수 정리 

## To-do
- [ ] 불필요한 함수 제거 
- [ ] 주석 제거 및 추가
- [ ] 반복되는 코드 함수로 

## ETC
기타 참고사항을 적어주세요.
