### ISSUE TITLE
[Feat] 홈 : 세부 일정 API

### ISSUE THREAD

**Issue by moonyaeyoon** [Here-You/here-you-backend#15]
## 이슈 번호 
#15
## Description
일정에 세부 일정을 추가해 작성하고 삭제할 수 있다.
완료 여부를 체크할 수 있다.

## To-do
- [ ] 세부 일정 추가하기 
- [ ] 세부 일정 작성하기
- [ ] 세부 일정 삭제하기
- [ ] 완료 여부 체크하기 

## ETC
기타 참고사항을 적어주세요.
