### ISSUE TITLE
[Fix] 여행 규칙 전체 리스트 : 나간 규칙 반영 안되는 에러

### ISSUE THREAD

**Issue by yewonahn** [Here-You/here-you-backend#197]
## Description
설명을 작성해주세요.

## To-do
- [x] sort 에러 해결
- [x] try catch 구조 확인
- [x] 사용자, 규칙, 수정/삭제/조회 권한 확인
- [x] 규칙 전체리스트 updated 날짜순으로 보여주기
