### ISSUE TITLE
[Refactor] 탐색, 메이트 탐색, 시그니처 탈퇴한 회원 필터링

### ISSUE THREAD

**Issue by JangYouJung** [Here-You/here-you-backend#230]
## Description
[Refactor] 탐색, 메이트 탐색, 시그니처 탈퇴한 회원 필터링

## To-do
- [ ] 탐색 메인: 인기/새로운 시그니처 커버 
- [ ] 탐색 : 키워드 검색
- [ ] 메이트 탐색: 장소기반/랜덤 메이트 추천
- [ ] 시그니처 댓글 불러오기

## ETC
기타 참고사항을 적어주세요.
