### ISSUE TITLE
[Refactor] 시그니처, 탐색: S3 이미지 업로드, 가져오기 구현 및 refactor

### ISSUE THREAD

**Issue by JangYouJung** [Here-You/here-you-backend#58]
## Description
기존 코드는 아무 문자열을 이미지 url로 반환했는데 
이미지를 서버에 업로드하고 가져오는 코드를 구현한다.

## To-do
- [ ] 시그니처 업로드에서 각 페이지 이미지 업로드 구현
- [ ] 시그니처 상세보기에서 각 페이지 이미지 가져오기 구현
- [ ] 시그니처, 탐색 화면에서 각 시그니처 커버 이미지 가져오기 구현

## ETC
2월 6일 화요일까지 마무리!
