### ISSUE TITLE
[FIX] 홈 : 예외 및 수정 사항 체크 

### ISSUE THREAD

**Issue by moonyaeyoon** [Here-You/here-you-backend#92]
## To-do
- [ ] 주석 추가 & 제거
- [ ] 사용 안 하는 함수들 삭제
- [ ] 예외 및 유효성 검사

## ETC
기타 참고사항을 적어주세요.
